# Generated by Django 4.0.2 on 2022-03-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importantyears', models.CharField(max_length=30)),
                ('conclusion', models.CharField(max_length=250)),
                ('famouspeople', models.CharField(max_length=50)),
            ],
        ),
    ]
