# Generated by Django 4.0.2 on 2022-03-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurt', '0002_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationalparks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=250)),
                ('datestarting', models.DateTimeField()),
            ],
        ),
    ]
